### ISSUE TITLE
CI is horribly inconsistent

### ISSUE THREAD

**Issue by jvanstraten** [mbrobbel/dqcsim#323]
Started the CI run for #322 two times, with different inane error messages. The first was caused by crates.io blocking azure for too many requests probably, HTTP 503. The second caused by the rust binding generation suddenly failing out of nowhere - but only for Python 3.6 on Linux, in a commit that changed nothing of the sort. This sort of thing is hardly the first time either. I don't know what's so messed up about our CI, but it's at the point where it has more false negatives than sane runs. It's kind of unworkable. The CI matrix should either be simplified considerably or the root problem needs to be fixed somehow.

**Comment by mbrobbel** [comment]
I'll try to move all our jobs to [Github Actions](https://help.github.com/en/actions), which enables potential enablement of our own [runners](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/hosting-your-own-runners) in the future.
