### ISSUE TITLE
Add Quantumsim backend

### ISSUE THREAD

**Issue by mbrobbel** [mbrobbel/dqcsim#89]
Tracking issue for the implementation of a [Quantumsim](https://github.com/quantumsim/quantumsim) backend plugin.

- [ ] Implement plugin
- [ ] Add tests
- [ ] Add documentation
- [ ] Publish plugin

**Comment by jvanstraten** [comment]
Work started [here](https://github.com/QE-Lab/dqcsim-quantumsim), TODO tracker [here](https://github.com/QE-Lab/dqcsim-quantumsim/issues/1).
